<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: immuni.proto

if (false) {
    /**
     * This class is deprecated. Use TemporaryExposureKey\ReportType instead.
     * @deprecated
     */
    class TemporaryExposureKey_ReportType {}
}
class_exists(TemporaryExposureKey\ReportType::class);
@trigger_error('TemporaryExposureKey_ReportType is deprecated and will be removed in the next major release. Use TemporaryExposureKey\ReportType instead', E_USER_DEPRECATED);

