<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: immuni.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TemporaryExposureKey</code>
 */
class TemporaryExposureKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes key_data = 1;</code>
     */
    protected $key_data = '';
    /**
     * Varying risk associated with a key depending on diagnosis method
     *
     * Generated from protobuf field <code>int32 transmission_risk_level = 2 [deprecated = true];</code>
     */
    protected $transmission_risk_level = 0;
    /**
     * The interval number since epoch for which a key starts
     *
     * Generated from protobuf field <code>int32 rolling_start_interval_number = 3;</code>
     */
    protected $rolling_start_interval_number = 0;
    /**
     * Increments of 10 minutes describing how long a key is valid
     *
     * Generated from protobuf field <code>int32 rolling_period = 4;</code>
     */
    protected $rolling_period = 0;
    /**
     * Type of diagnosis associated with a key.
     *
     * Generated from protobuf field <code>.TemporaryExposureKey.ReportType report_type = 5;</code>
     */
    protected $report_type = 0;
    /**
     * Number of days elapsed between symptom onset and the TEK being used.
     * E.g. 2 means TEK is 2 days after onset of symptoms.
     *
     * Generated from protobuf field <code>sint32 days_since_onset_of_symptoms = 6;</code>
     */
    protected $days_since_onset_of_symptoms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_data
     *           Key of infected user
     *     @type int $transmission_risk_level
     *           Varying risk associated with a key depending on diagnosis method
     *     @type int $rolling_start_interval_number
     *           The interval number since epoch for which a key starts
     *     @type int $rolling_period
     *           Increments of 10 minutes describing how long a key is valid
     *     @type int $report_type
     *           Type of diagnosis associated with a key.
     *     @type int $days_since_onset_of_symptoms
     *           Number of days elapsed between symptom onset and the TEK being used.
     *           E.g. 2 means TEK is 2 days after onset of symptoms.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Immuni::initOnce();
        parent::__construct($data);
    }

    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes key_data = 1;</code>
     * @return string
     */
    public function getKeyData()
    {
        return $this->key_data;
    }

    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes key_data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyData($var)
    {
        GPBUtil::checkString($var, False);
        $this->key_data = $var;

        return $this;
    }

    /**
     * Varying risk associated with a key depending on diagnosis method
     *
     * Generated from protobuf field <code>int32 transmission_risk_level = 2 [deprecated = true];</code>
     * @return int
     */
    public function getTransmissionRiskLevel()
    {
        return $this->transmission_risk_level;
    }

    /**
     * Varying risk associated with a key depending on diagnosis method
     *
     * Generated from protobuf field <code>int32 transmission_risk_level = 2 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setTransmissionRiskLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->transmission_risk_level = $var;

        return $this;
    }

    /**
     * The interval number since epoch for which a key starts
     *
     * Generated from protobuf field <code>int32 rolling_start_interval_number = 3;</code>
     * @return int
     */
    public function getRollingStartIntervalNumber()
    {
        return $this->rolling_start_interval_number;
    }

    /**
     * The interval number since epoch for which a key starts
     *
     * Generated from protobuf field <code>int32 rolling_start_interval_number = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRollingStartIntervalNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->rolling_start_interval_number = $var;

        return $this;
    }

    /**
     * Increments of 10 minutes describing how long a key is valid
     *
     * Generated from protobuf field <code>int32 rolling_period = 4;</code>
     * @return int
     */
    public function getRollingPeriod()
    {
        return $this->rolling_period;
    }

    /**
     * Increments of 10 minutes describing how long a key is valid
     *
     * Generated from protobuf field <code>int32 rolling_period = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRollingPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->rolling_period = $var;

        return $this;
    }

    /**
     * Type of diagnosis associated with a key.
     *
     * Generated from protobuf field <code>.TemporaryExposureKey.ReportType report_type = 5;</code>
     * @return int
     */
    public function getReportType()
    {
        return $this->report_type;
    }

    /**
     * Type of diagnosis associated with a key.
     *
     * Generated from protobuf field <code>.TemporaryExposureKey.ReportType report_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setReportType($var)
    {
        GPBUtil::checkEnum($var, \TemporaryExposureKey_ReportType::class);
        $this->report_type = $var;

        return $this;
    }

    /**
     * Number of days elapsed between symptom onset and the TEK being used.
     * E.g. 2 means TEK is 2 days after onset of symptoms.
     *
     * Generated from protobuf field <code>sint32 days_since_onset_of_symptoms = 6;</code>
     * @return int
     */
    public function getDaysSinceOnsetOfSymptoms()
    {
        return $this->days_since_onset_of_symptoms;
    }

    /**
     * Number of days elapsed between symptom onset and the TEK being used.
     * E.g. 2 means TEK is 2 days after onset of symptoms.
     *
     * Generated from protobuf field <code>sint32 days_since_onset_of_symptoms = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDaysSinceOnsetOfSymptoms($var)
    {
        GPBUtil::checkInt32($var);
        $this->days_since_onset_of_symptoms = $var;

        return $this;
    }

}

